name: publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: nathanielwroblewski/eks-helm-command
          tag_with_ref: true
