name: publish

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: Docker image tag to publish

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: docker-hub
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: nathanielwroblewski/eks-helm-command:${{ github.event.inputs.tag }}
